### ISSUE TITLE
Issue during ./make.py

### ISSUE THREAD

**Issue by Amrizhan** [mapbox/osm-bright#105]
Hi there, when i tried to do ./make.py I have next error:

zhandos@root-osm:/usr/local/share/maps/style/osm-bright-master$ ./make.py
Traceback (most recent call last):
  File "./make.py", line 123, in <module>
    build()
  File "./make.py", line 41, in build
    template = loads(templatefile.read())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 8 column 19 (char 298)

line 8 in my osmbright is: 
'from json import loads, dumps

**Comment by DaviKaur** [comment]
I'm facing the same problem, in line 9. I've checked the code, its correct. What should I do to resolve this error?

**Comment by DaviKaur** [comment]
Code is correct. Check your file - /usr/local/share/maps/style/osm-bright-master/osm-bright/osm-bright.osm2pgsql.mml Check what you've edited, pasted in a correct way or not. Are you using proper delimiters at the end of "type":"shape". Similarly, are using correct property name. Check your file. These is no issue in code.

**Comment by rikkitikkitumbo** [comment]
ahh... for what it's worth I'm getting a similar error:

jeff@jeff-Inspiron-5749:~/Documents/mapbox-osm-bright-f1c8780$ ./make.py 
<open file 'osm-bright/osm-bright.imposm.mml', mode 'r' at 0x7fab16ed4db0>
Traceback (most recent call last):
  File "./make.py", line 129, in <module>
    build()
  File "./make.py", line 42, in build
    template = loads(templatefile.read())
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 554 column 7 (char 26688)

I think they're talking about this line:
"geometry": "point",
      "Datasource": {
        "type": "postgis",
        "table": "( SELECT geometry, type, name \n  FROM osm_transport_points \n  WHERE type='station'\n) AS DATA ",
        "key_field": "",
        "geometry_field": "geometry",
        "extent": "-20037508.34 -20037508.34 20037508.34 20037508.34",
      },    ***_((((is line 554)))))**_****
      "id": "train_stations",
      "class": "",
      "srs-name": "900913",

but it looks ok to me, so I'm not sure what to do

**Comment by rikkitikkitumbo** [comment]
Whoop!!!  look at this:

"extent": "-20037508.34 -20037508.34 20037508.34 20037508.34",
},

needs to be changed to:
"extent": "-20037508.34 -20037508.34 20037508.34 20037508.34"
},  (no comma after 34 there... this isn't important in javascript, but apparently it means something here...)

**Comment by tyler-laws** [comment]
I made a pull request to fix this Aug 28.

**Comment by rikkitikkitumbo** [comment]
Hey, I'm trying to make a custom map... Any advice?  I've got myself up and running with this tutorial: https://tilemill-project.github.io/tilemill/docs/guides/osm-bright-ubuntu-quickstart/   but I'm wondering if there's something better out there than tilemill... it's pretty slow.

**Comment by tyler-laws** [comment]
I have had success with Mapproxy. It can run w/ Mapnik directly or be set up w/ Tilemill, check out https://mapproxy.org/. 

I currently use Mapproxy w/ Mapserver, quick demo here: http://tylerlaws.ddns.net, which I will leave up for a day. Feel free to contact me by email at tyler.laws@outlook.com if you have questions or need help, I would be happy to assist.

**Comment by tyler-laws** [comment]
Fixed demo, tiles weren't available but should be okay now.
