### ISSUE TITLE
Malformed json in imposm.mml

### ISSUE THREAD

**Issue by ssipos90** [mapbox/osm-bright#135]
Hi,

In `osm-bright/osm-bright.imposm.mml` there's a trailing comma on line 553.
```json 
....
552:        "geometry_field": "geometry",
553:        "extent": "-20037508.34 -20037508.34 20037508.34 20037508.34",
554:      },
...
```

And ./make.py fails with:
```
Traceback (most recent call last):
  File "./make.py", line 128, in <module>
    build()
  File "./make.py", line 41, in build
    template = loads(templatefile.read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 554 column 7 (char 26688)
The command 'python2 ./make.py' returned a non-zero code: 1
```

**Comment by ssipos90** [comment]
Most probably, the python lib got upgraded and doesn't allow this anymore - basically sticking to JSON specs.
