### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by AlysonTrizotto** [mapbox/osm-bright#137]
I've been having the same return for a long time, I checked the installations, read the read.me, but I still couldn't install. This is the payback I have:

`C:\Users\PESSOAL\Downloads\mapbox-osm-bright-f1c8780>make.py
Traceback (most recent call last):
  File "C:\Users\PESSOAL\Downloads\mapbox-osm-bright-f1c8780\make.py", line 129, in <module>
    install()
  File "C:\Users\PESSOAL\Downloads\mapbox-osm-bright-f1c8780\make.py", line 67, in install
    assert isdir(config["path"]), "Config.path does not point to your mapbox projects directory; please fix and re-run"
AssertionError: Config.path does not point to your mapbox projects directory; please fix and re-run`

this is my "configure.py"
[configure.txt](https://github.com/mapbox/osm-bright/files/8377171/configure.txt)

this is my dependencies 
![Capturar](https://user-images.githubusercontent.com/79091765/160755613-c9a1ef87-7425-452c-bbc4-7e413857b222.PNG)

**Comment by donno** [comment]
Check that the "path" you set in configure.py exists and is a directory.

The relevant part was:
```
config["path"] = path.expanduser("~/Documents/MapBox/project")
```

So in your Documents folder create a folder called `MapBox` if it doesn't already exist and then create a folder called `project` within that.

The message could be improved to explain that the folder must exist, as its very subtle that that is what 'isdir()' is looking for (i.e that it is a directory that already exists).
